### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by justbrowsing37** [SophieCodingg/bombparty-helpbot#1]
Im jst trying to figure out how to run it of my own instance?
Just trying to set it up on my own to propose changes

**Comment by justbrowsing37** [comment]
It should just be the chrome driver right?
download and run?

**Comment by AgustinCoding** [comment]
Install dependencies (pip install selenium re random) and just look up in
youtube how to set up chrome driver, it needs to match your google chrome
version. Just put chromedriver.exe in the project file and run main.py

**Comment by AgustinCoding** [comment]
I didn’t compile it to an exe file yet, we can do it in a future so it’s
more intuitive

**Comment by justbrowsing37** [comment]
@AgustinCode 

Have you started to work on optimizations yet? or are you just trying to finish the chrome driver for now?

**Comment by AgustinCoding** [comment]
No i haven't, i just made it work today because i was getting a lot of errors. That's something i need to work on, the driver part is already done, you can add more commands directly in the function 'process_message'. I need to work on optimization, i might replace time sleeps with WebDriverWait. I also need to add more documentation
